# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='short_url',
            field=models.CharField(blank=True, default=b'No url', max_length=32, unique=True),
        ),
    ]
