# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0002_auto_20171005_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
