# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import shortener_app.validator


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0004_auto_20171005_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener_app.validator.validate_url]),
        ),
    ]
